<a href="https://colab.research.google.com/github/hasune613/hello-world/blob/main/%E6%97%A5%E6%9C%AC%E8%AA%9EBERT%E3%81%A7livedoor%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%B9%E3%82%92%E7%9B%B8%E4%BA%92%E6%83%85%E5%A0%B1%E9%87%8F%E6%9C%80%E5%A4%A7%E5%8C%96(IIC)%E3%81%A7%E3%82%AF%E3%83%A9%E3%82%B9%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 乱数シードの固定

import os
import random
import numpy as np
import torch

SEED_VALUE = 1234  # これはなんでも良い
os.environ['PYTHONHASHSEED'] = str(SEED_VALUE)
random.seed(SEED_VALUE)
np.random.seed(SEED_VALUE)
torch.manual_seed(SEED_VALUE)  # PyTorchを使う場合

In [2]:
torch.cuda.is_available()


True

In [3]:
! wget "https://www.rondhuit.com/download/ldcc-20140209.tar.gz"

--2022-01-25 22:41:36--  https://www.rondhuit.com/download/ldcc-20140209.tar.gz
Resolving www.rondhuit.com (www.rondhuit.com)... 59.106.19.174
Connecting to www.rondhuit.com (www.rondhuit.com)|59.106.19.174|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8855190 (8.4M) [application/x-gzip]
Saving to: ‘ldcc-20140209.tar.gz’

ldcc-20140209.tar.g 100%[===================>]   8.44M  1.88MB/s    in 4.5s    

2022-01-25 22:41:42 (1.88 MB/s) - ‘ldcc-20140209.tar.gz’ saved [8855190/8855190]



In [4]:
import tarfile
import os

In [5]:
tar = tarfile.open('/content/ldcc-20140209.tar.gz', 'r:gz')
tar.extractall('./data/livedoor/')
tar.close

<bound method TarFile.close of <tarfile.TarFile object at 0x7fe9903127d0>>

In [6]:
files_folders =[name for name in os.listdir('/content/data/livedoor/text/')]
print(files_folders)

['kaden-channel', 'livedoor-homme', 'smax', 'sports-watch', 'dokujo-tsushin', 'movie-enter', 'README.txt', 'it-life-hack', 'peachy', 'CHANGES.txt', 'topic-news']


In [7]:
categories = [name for name in os.listdir('/content/data/livedoor/text') if os.path.isdir('/content/data/livedoor/text/' + name)]
print(categories)
print('カテゴリー数 : ',len(categories))

['kaden-channel', 'livedoor-homme', 'smax', 'sports-watch', 'dokujo-tsushin', 'movie-enter', 'it-life-hack', 'peachy', 'topic-news']
カテゴリー数 :  9


In [8]:
file_name =  '/content/data/livedoor/text/movie-enter/movie-enter-6255260.txt'

with open(file_name) as text_file:
    text = text_file.readlines()
    print('0:',text[0]) # URL
    print('1:',text[1]) # タイムスタンプ
    print('2:',text[2]) # タイトル
    print('3:',text[3]) # 本文

0: http://news.livedoor.com/article/detail/6255260/

1: 2012-02-07T09:00:00+0900

2: 新しいヴァンパイアが誕生！　ジョニデ主演『ダーク・シャドウ』の公開日が決定

3: 　こんなヴァンパイアは見たことがない！　ジョニー・デップとティム・バートン監督がタッグを組んだ映画『ダーク・シャドウズ（原題）』の邦題が『ダーク・シャドウ』に決定。日本公開日が5月19日に決まった。さらに、ジョニー・デップ演じるヴァンパイアの写真が公開された。



In [9]:
# 本文抽出

def extract_main_txt(file_name):
    with open(file_name) as text_file:
        text = text_file.readlines()[3:]

        text = [sentence.strip() for sentence in text]
        text = list(filter(lambda line : line != '', text))
        text = ''.join(text)
        text = text.translate(str.maketrans(
            {'\n':'','\t':'','\r':'','\u3000':''}
        ))
        return text

In [10]:
import glob

In [11]:
list_text = []
list_label = []

for cat in categories:
    text_files = glob.glob(os.path.join('/content/data/livedoor/text',cat,'*.txt'))
    body = [ extract_main_txt(text_file) for text_file in text_files ]
    label = [cat] * len(body)
    list_text.extend(body)
    list_label.extend(label)

In [12]:
print(list_text[0])
print(list_label[0])

人気ロックバンドLUNA SEAが１２年振りとなる新曲をリリースすると２０日の０時にHP上で発表した。久しぶりのリリースに楽曲そのものへの期待はもちろんだが、注目したいのは音質の違う複数のCDを販売するという点だ。音質は３種類あり、ノーマルCDバージョン、高音質ステレオ音源によるハイ・クオリティCDバージョン、さらに高音質5.1chサラウンド音源による5.1chサラウンドCDバージョンとなっている。LUNA SEAのメンバーは以前よりインタビューなどで「自分たちのファンは耳が肥えている」とコメントしていたが、CDをただの商品としてではなく楽しみ方までこだわるところに本人たちの音楽一筋という姿勢が見える。音楽以外の特典を付けて販売する手法が増えているなか、音楽そのものを楽しむために仕様を変えて販売するというこの試みは要注目。なお、この新曲のタイトルはまだ決まっていないが、２０分にも及ぶ大作だということだ。■ノーマルCDバージョン¥1,260 (税込)ハイ・クオリティCDバージョン (高音質ステレオ音源)¥1,575 (税込)5.1chサラウンドCDバージョン (高音質5.1chサラウンド音源）¥1,890 (税込)BRAND NEW SINGLE 2012.03.21 リリース決定!!（LUNA SEAHP）■関連記事・ネットはバカ発見器？SNSの普及で拡大する実名制に要注意【話題】・スマホを自分で除菌するのが新常識に！？手軽な小型紫外線滅菌器「UVサニタイザー」がオススメ【売れ筋チェック】・YES！高須度チェック！予想の斜め上を行く高須クリニックのスペシャルサイトに困惑【話題】・iPhoneを本格的なカメラに変えるかわいすぎるケースが登場！【売れ筋】・楽しいことにもいつかは終わりが・・・Google「Picnik」終了のお知らせが気になる【話題】
kaden-channel


In [13]:
import pandas as pd

df = pd.DataFrame({'text' : list_text, 'label' : list_label})
print(df.shape)
df.head(3)

(7376, 2)


text          label
0  人気ロックバンドLUNA SEAが１２年振りとなる新曲をリリースすると２０日の０時にHP上で...  kaden-channel
1  リサーチ会社のGfKJapanが発表した10月11日から16日までのレポートによると、この期...  kaden-channel
2  春は新生活がスタートする季節です。進学や就職で一人暮らしを始める人も多く、引っ越しする人も、...  kaden-channel

In [14]:
dic_id2cat = dict( zip(list(range(len(categories))),categories))
dic_cat2id = dict( zip(categories, list(range(len(categories)))))

print(dic_id2cat)
print(dic_cat2id)

{0: 'kaden-channel', 1: 'livedoor-homme', 2: 'smax', 3: 'sports-watch', 4: 'dokujo-tsushin', 5: 'movie-enter', 6: 'it-life-hack', 7: 'peachy', 8: 'topic-news'}
{'kaden-channel': 0, 'livedoor-homme': 1, 'smax': 2, 'sports-watch': 3, 'dokujo-tsushin': 4, 'movie-enter': 5, 'it-life-hack': 6, 'peachy': 7, 'topic-news': 8}


In [15]:
df['label_index'] = df['label'].map(dic_cat2id)
df.head()

text  ... label_index
0  人気ロックバンドLUNA SEAが１２年振りとなる新曲をリリースすると２０日の０時にHP上で...  ...           0
1  リサーチ会社のGfKJapanが発表した10月11日から16日までのレポートによると、この期...  ...           0
2  春は新生活がスタートする季節です。進学や就職で一人暮らしを始める人も多く、引っ越しする人も、...  ...           0
3  非常用ＬＥＤ照明のヒット商品マジックバルブ（懐中電灯兼用ＬＥＤライト）を手がける（株）ラブロ...  ...           0
4  中野 森（しん）監督が「藤沢シネマ」の企画書を提出したのは3月のこと。当初から秋をテーマにし...  ...           0

[5 rows x 3 columns]

In [16]:
df = df.loc[:, ['text', 'label_index']]
df.head()

text  label_index
0  人気ロックバンドLUNA SEAが１２年振りとなる新曲をリリースすると２０日の０時にHP上で...            0
1  リサーチ会社のGfKJapanが発表した10月11日から16日までのレポートによると、この期...            0
2  春は新生活がスタートする季節です。進学や就職で一人暮らしを始める人も多く、引っ越しする人も、...            0
3  非常用ＬＥＤ照明のヒット商品マジックバルブ（懐中電灯兼用ＬＥＤライト）を手がける（株）ラブロ...            0
4  中野 森（しん）監督が「藤沢シネマ」の企画書を提出したのは3月のこと。当初から秋をテーマにし...            0

In [17]:
df = df.sample(frac=1, random_state=123).reset_index(drop=True)
df.head()

text  label_index
0  タレントの小森純が21日、都内で行われた映画『グレイヴ・エンカウンターズ』の公開記念イベント...            5
1  スマートフォンのユーザーの中には、手軽にスマートフォンの画面を見たい人もいるだろう。そういう...            6
2  11日、J1浦和は1FCケルン（ドイツ）から日本代表DF槙野智章を期限付き移籍で獲得したこと...            3
3  ジョニデとティム・バートン監督に会えるチャンス！『チャーリーとチョコレート工場』『アリス・イ...            5
4  バットマンやスパイダーマン、そして、日本のスーパー戦隊や仮面ライダーたち、彼らはいずれも特徴...            5

In [18]:
len_0_2 = len(df) // 5
len_0_2 #1475

df[:len_0_2].to_csv('./test.tsv', sep='\t', index=False,header=None)
print(df[:len_0_2].shape)
df[len_0_2:].to_csv('./train_eval.tsv',sep='\t', index=False, header=None)
print(df[len_0_2:].shape)

(1475, 2)
(5901, 2)


In [19]:
df[:len_0_2].head(3)

text  label_index
0  タレントの小森純が21日、都内で行われた映画『グレイヴ・エンカウンターズ』の公開記念イベント...            5
1  スマートフォンのユーザーの中には、手軽にスマートフォンの画面を見たい人もいるだろう。そういう...            6
2  11日、J1浦和は1FCケルン（ドイツ）から日本代表DF槙野智章を期限付き移籍で獲得したこと...            3

In [20]:
df[len_0_2:].head(3)

text  label_index
1475  8日、フジテレビ「とくダネ！」には、体操日本代表メンバー＝内村航平、田中和仁、田中佑典、加藤...            3
1476  入社式から約2ヵ月。今年の新入社員の様子はどうだろうか？ 公益財団法人日本生産性本部によれば...            4
1477  LUMIX Phone P-02Dにソフトウェア更新！NTTドコモは5日、パナソニックのデジ...            2

In [21]:
# from google.colab import files
# files.download("./test.tsv")
# files.download("./train_eval.tsv")

In [22]:
!apt install aptitude swig
!aptitude install mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file -y
!pip install mecab-python3
!pip install "transformers==4.9.1"

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aptitude-common libcgi-fast-perl libcgi-pm-perl libclass-accessor-perl
  libcwidget3v5 libencode-locale-perl libfcgi-perl libhtml-parser-perl
  libhtml-tagset-perl libhttp-date-perl libhttp-message-perl libio-html-perl
  libio-string-perl liblwp-mediatypes-perl libparse-debianchangelog-perl
  libsigc++-2.0-0v5 libsub-name-perl libtimedate-perl liburi-perl libxapian30
  swig3.0
Suggested packages:
  aptitude-doc-en | aptitude-doc apt-xapian-index debtags tasksel
  libcwidget-dev libdata-dump-perl libhtml-template-perl libxml-simple-perl
  libwww-perl xapian-tools swig-doc swig-examples swig3.0-examples swig3.0-doc
The following NEW packages will be installed:
  aptitude aptitude-common libcgi-fast-perl libcgi-pm-perl
  libclass-accessor-perl libcwidget3v5 libencode-locale-perl libfcgi-perl
  libhtml-parser-perl libhtml-tagset-perl libhttp

In [23]:
!pip install fugashi
!pip install ipadic

     |████████████████████████████████| 490 kB 14.1 MB/s 
     |████████████████████████████████| 13.4 MB 16.4 MB/s 
  Created wheel for ipadic: filename=ipadic-1.0.0-py3-none-any.whl size=13556723 sha256=01539b7fa7e17dc5d83cb056c34d0232069479e07226b99233c1045edc37a9b8
  Stored in directory: /root/.cache/pip/wheels/33/8b/99/cf0d27191876637cd3639a560f93aa982d7855ce826c94348b
Successfully built ipadic


In [24]:
import torch
import torchtext  # torchtextを使用
#from transformers.modeling_bert import BertModel
from transformers import BertJapaneseTokenizer

# 日本語BERTの分かち書き用tokenizerです
tokenizer = BertJapaneseTokenizer.from_pretrained('cl-tohoku/bert-base-japanese-whole-word-masking',
     mecab_kwargs={"mecab_dic": "ipadic", "mecab_option": None})                                              
    

Downloading:   0%|          | 0.00/258k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/110 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/479 [00:00<?, ?B/s]

In [25]:
# データを読み込んだときに、読み込んだ内容に対して行う処理を定義します

max_length = 512  # 東北大学_日本語版の最大の単語数（サブワード数）は512


def tokenizer_512(input_text):
    """torchtextのtokenizerとして扱えるように、512単語のpytorchでのencodeを定義。ここで[0]を指定し忘れないように"""
    return tokenizer.encode(input_text, max_length=512, return_tensors='pt')[0]


TEXT = torchtext.legacy.data.Field(sequential=True, tokenize=tokenizer_512, use_vocab=False, lower=False,
                            include_lengths=True, batch_first=True, fix_length=max_length, pad_token=0)
# 注意：tokenize=tokenizer.encodeと、.encodeをつけます。padding[PAD]のindexが0なので、0を指定します。

LABEL = torchtext.legacy.data.Field(sequential=False, use_vocab=False)

# (注釈)：各引数を再確認
# sequential: データの長さが可変か？文章は長さがいろいろなのでTrue.ラベルはFalse
# tokenize: 文章を読み込んだときに、前処理や単語分割をするための関数を定義
# use_vocab：単語をボキャブラリーに追加するかどうか
# lower：アルファベットがあったときに小文字に変換するかどうか
# include_length: 文章の単語数のデータを保持するか
# batch_first：ミニバッチの次元を用意するかどうか
# fix_length：全部の文章をfix_lengthと同じ長さになるように、paddingします
# init_token, eos_token, pad_token, unk_token：文頭、文末、padding、未知語に対して、どんな単語を与えるかを指定

In [26]:
# 各tsvファイルを読み込み、分かち書きをしてdatasetにします
# 少し時間がかかります
# train_eval：5901個、test：1475個
dataset_train_eval, dataset_test = torchtext.legacy.data.TabularDataset.splits(
    path='.', train='train_eval.tsv', test='test.tsv', format='tsv', fields=[('Text', TEXT), ('Label', LABEL)])

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [27]:
# torchtext.data.Datasetのsplit関数で訓練データと検証データを分ける
# train_eval：5901個、test：1475個

dataset_train, dataset_eval = dataset_train_eval.split(
    split_ratio=1.0 - 1475/5901, random_state=random.seed(1234))

# datasetの長さを確認してみる
print(dataset_train.__len__())
print(dataset_eval.__len__())
print(dataset_test.__len__())

4426
1475
1475


In [28]:
# DataLoaderを作成します（torchtextの文脈では単純にiteraterと呼ばれています）
batch_size = 16  # BERTでは16、32あたりを使用する

dl_train = torchtext.legacy.data.Iterator(
    dataset_train, batch_size=batch_size, train=True)

dl_eval = torchtext.legacy.data.Iterator(
    dataset_eval, batch_size=batch_size, train=False, sort=False)

dl_test = torchtext.legacy.data.Iterator(
    dataset_test, batch_size=batch_size, train=False, sort=False)

# 辞書オブジェクトにまとめる
dataloaders_dict = {"train": dl_train, "val": dl_eval}

In [41]:
from transformers.models.bert.modeling_bert import BertModel

# BERTの日本語学習済みパラメータのモデルです
model = BertModel.from_pretrained('cl-tohoku/bert-base-japanese-whole-word-masking')
# model = BertModel.from_pretrained('bert-base-japanese-whole-word-masking')
model.eval()
print('ネットワーク設定完了')

Some weights of the model checkpoint at cl-tohoku/bert-base-japanese-whole-word-masking were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


ネットワーク設定完了


In [42]:
# BERTでベクトル化する関数を定義


def vectorize_with_bert(net, dataloader):

    # GPUが使えるかを確認
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print("使用デバイス：", device)
    print('-----start-------')

    # ネットワークをGPUへ
    net.to(device)

    # ネットワークがある程度固定であれば、高速化させる
    torch.backends.cudnn.benchmark = True

    # ミニバッチのサイズ
    batch_size = dataloader.batch_size

    # データローダーからミニバッチを取り出すループ
    for index, batch in enumerate(dataloader):
        # batchはTextとLableの辞書オブジェクト
        device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
        inputs = batch.Text[0].to(device)  # 文章
        labels = batch.Label.to(device)  # ラベル

        # 順伝搬（forward）計算
        with torch.set_grad_enabled(False):

            # Berに入力
            result = net(inputs)

            # sequence_outputの先頭の単語ベクトルを抜き出す
            vec_0 = result[0]  # 最初の0がsequence_outputを示す
            vec_0 = vec_0[:, 0, :]  # 全バッチ。先頭0番目の単語の全768要素
            vec_0 = vec_0.view(-1, 768)  # sizeを[batch_size, hidden_size]に変換

            # ベクトル化したデータをtorchリストにまとめる
            if index == 0:
                list_text = vec_0
                list_label = labels
            else:
                list_text = torch.cat([list_text, vec_0], dim=0)
                list_label = torch.cat([list_label, labels], dim=0)

    return list_text, list_label

In [43]:
# DataLoaderをベクトル化版に変換
# 少し時間がかかります5分弱

list_text_train, list_label_train = vectorize_with_bert(model, dl_train)
list_text_eval, list_label_eval = vectorize_with_bert(model, dl_eval)
list_text_test, list_label_test = vectorize_with_bert(model, dl_test)

使用デバイス： cuda:0
-----start-------
使用デバイス： cuda:0
-----start-------
使用デバイス： cuda:0
-----start-------


In [44]:
# torchのリストをDatasetに変換

from torch.utils.data import TensorDataset

dataset_bert_train = TensorDataset(
    list_label_train.view(-1, 1), list_text_train)
dataset_bert_eval = TensorDataset(list_label_eval.view(-1, 1), list_text_eval)
dataset_bert_test = TensorDataset(list_label_test.view(-1, 1), list_text_test)

In [45]:
# Dataloaderにする
from torch.utils.data import DataLoader

batch_size = 1024

dl_bert_train = DataLoader(
    dataset_bert_train, batch_size=batch_size, shuffle=True, drop_last=True)
# drop_lastは最後のミニバッチがbatch_sizeに足りない場合は無視する

dl_bert_eval = DataLoader(
    dataset_bert_eval, batch_size=batch_size, shuffle=False)
dl_bert_test = DataLoader(
    dataset_bert_test, batch_size=batch_size, shuffle=False)

In [46]:
import torch.nn as nn
import torch.nn.functional as F

OVER_CLUSTRING_RATE = 10


class NetIIC(nn.Module):
    def __init__(self):
        super(NetIIC, self).__init__()

        # multi-headは今回しない
        self.conv1 = nn.Conv1d(1, 400, kernel_size=768, stride=1, padding=0)
        self.bn1 = nn.BatchNorm1d(400)
        self.conv2 = nn.Conv1d(1, 300, kernel_size=400, stride=1, padding=0)
        self.bn2 = nn.BatchNorm1d(300)
        self.conv3 = nn.Conv1d(1, 300, kernel_size=300, stride=1, padding=0)
        self.bn3 = nn.BatchNorm1d(300)

        self.fc1 = nn.Linear(300, 250)
        self.bnfc1 = nn.BatchNorm1d(250)

        # livedoorニュースの9カテゴリに対応するかな？と期待する9分類
        self.fc2 = nn.Linear(250, 9)

        # overclustering
        # 実際の想定よりも多めにクラスタリングさせることで、ネットワークで微細な変化を捉えられるようにする
        self.fc2_overclustering = nn.Linear(250, 9*OVER_CLUSTRING_RATE)

    def forward(self, x):
        x = x.view(x.size(0), 1, -1)
        x = F.relu(self.bn1(self.conv1(x)))

        x = x.view(x.size(0), 1, -1)
        x = F.relu(self.bn2(self.conv2(x)))

        x = x.view(x.size(0), 1, -1)
        x = F.relu(self.bn3(self.conv3(x)))

        x = x.view(x.size(0), -1)
        x_prefinal = F.relu(self.bnfc1(self.fc1(x)))

        # multi-headは使わず
        y = F.softmax(self.fc2(x_prefinal), dim=1)
        y_overclustering = F.softmax(self.fc2_overclustering(
            x_prefinal), dim=1)  # overclustering

        return y, y_overclustering

In [47]:
import torch.nn.init as init


def weight_init(m):
    """重み初期化"""
    if isinstance(m, nn.Conv1d):
        init.normal_(m.weight.data)
        if m.bias is not None:
            init.normal_(m.bias.data)
    elif isinstance(m, nn.BatchNorm1d):
        init.normal_(m.weight.data, mean=1, std=0.02)
        init.constant_(m.bias.data, 0)
    elif isinstance(m, nn.Linear):
        # Xavier
        # init.xavier_normal_(m.weight.data)

        # He
        init.kaiming_normal_(m.weight.data)

        if m.bias is not None:
            init.normal_(m.bias.data)

In [48]:
# IISによる損失関数の定義
# 参考：https://github.com/RuABraun/phone-clustering/blob/master/mnist_basic.py
import sys


def compute_joint(x_out, x_tf_out):
    bn, k = x_out.size()
    assert (x_tf_out.size(0) == bn and x_tf_out.size(1) == k), '{} {} {} {}'.format(
        bn, k, x_tf_out.size(0), x_tf_out.size(1))

    p_i_j = x_out.unsqueeze(2) * x_tf_out.unsqueeze(1)  # bn, k, k
    p_i_j = p_i_j.sum(dim=0)  # k, k
    p_i_j = (p_i_j + p_i_j.t()) / 2.  # symmetrise
    p_i_j = p_i_j / p_i_j.sum()  # normalise
    return p_i_j


def IID_loss(x_out, x_tf_out, EPS=sys.float_info.epsilon):
    # has had softmax applied
    bs, k = x_out.size()
    p_i_j = compute_joint(x_out, x_tf_out)
    assert (p_i_j.size() == (k, k))

    p_i = p_i_j.sum(dim=1).view(k, 1).expand(k, k)
    p_j = p_i_j.sum(dim=0).view(1, k).expand(k, k)

    # avoid NaN losses. Effect will get cancelled out by p_i_j tiny anyway
    # これはPyTorchのバージョン1.3以上だとエラーになる
    # https://discuss.pytorch.org/t/pytorch-1-3-showing-an-error-perhaps-for-loss-computed-from-paired-outputs/68790/3
    #p_i_j[(p_i_j < EPS).data] = EPS
    #p_j[(p_j < EPS).data] = EPS
    #p_i[(p_i < EPS).data] = EPS

    p_i_j = torch.where(p_i_j < EPS, torch.tensor(
        [EPS], device=p_i_j.device), p_i_j)
    p_j = torch.where(p_j < EPS, torch.tensor([EPS], device=p_j.device), p_j)
    p_i = torch.where(p_i < EPS, torch.tensor([EPS], device=p_i.device), p_i)

    # https://qiita.com/Amanokawa/items/0aa24bc396dd88fb7d2a
    # 参考に、重みalphaを追加

    alpha = 2.0
    loss = (- p_i_j * (torch.log(p_i_j) - alpha *
                       torch.log(p_j) - alpha*torch.log(p_i))).sum()

    return loss

In [49]:
# データにノイズを加える関数の定義
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor_std = list_text_train.std(dim=0).to(device)


def perturb_data(x):
    y = x.clone()
    noise = torch.randn(len(tensor_std)).to(device)*tensor_std*2.0
    noise = noise.expand(x.shape[0], -1)
    y += noise

    return y

In [50]:
# 学習関数の定義

def train(total_epoch, model, train_loader, optimizer, device):

    # ネットワークを訓練モードに
    model.train()

    # 学習率のスケジューラーCosAnnealing
    scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(
        optimizer, T_0=2, T_mult=2, eta_min=0)

    for epoch in range(total_epoch):
        for batch_idx, (target, data) in enumerate(train_loader):

            # 学習率変化
            scheduler.step()
            
            data_perturb = perturb_data(data)  # ノイズを与え、変換したデータを作る

            # GPUに送れる場合は送る
            data = data.to(device)
            data_perturb = data_perturb.to(device)

            # 最適化関数の初期化
            optimizer.zero_grad()

            # ニューラルネットワークへ入れる
            output, output_overclustering = model(data)
            output_perturb, output_perturb_overclustering = model(data_perturb)

            # 損失の計算
            loss1 = IID_loss(output, output_perturb)
            loss2 = IID_loss(output_overclustering,
                             output_perturb_overclustering)
            loss = loss1 + loss2

            # 損失を減らすように更新
            loss.backward()
            optimizer.step()

        # ログ出力
        if epoch % 50 == 0:
            print('Train Epoch {} \tLoss1: {:.6f} \tLoss2: {:.6f} \tLoss_total: {:.6f}'.format(
                epoch, loss1.item(), loss2.item(), loss1.item()+loss2.item()))

    return model, optimizer

In [51]:
# 学習の実施(5分弱)

# モデルの用意
net = NetIIC()
net.apply(weight_init)
net.to(device)

# 最適化関数
optimizer = torch.optim.Adam(net.parameters(), lr=5e-4) 

total_epoch = 1000

model_trained, optimizer = train(
    total_epoch, net, dl_bert_train, optimizer, device)

Train Epoch 0 	Loss1: -3.939305 	Loss2: -8.418325 	Loss_total: -12.357631
Train Epoch 50 	Loss1: -6.191078 	Loss2: -10.284426 	Loss_total: -16.475503
Train Epoch 100 	Loss1: -6.513981 	Loss2: -11.597788 	Loss_total: -18.111769
Train Epoch 150 	Loss1: -6.540277 	Loss2: -12.262718 	Loss_total: -18.802995
Train Epoch 200 	Loss1: -6.564394 	Loss2: -12.763287 	Loss_total: -19.327681
Train Epoch 250 	Loss1: -6.528029 	Loss2: -12.860191 	Loss_total: -19.388221
Train Epoch 300 	Loss1: -6.565479 	Loss2: -13.287652 	Loss_total: -19.853131
Train Epoch 350 	Loss1: -6.560932 	Loss2: -13.285703 	Loss_total: -19.846634
Train Epoch 400 	Loss1: -6.578548 	Loss2: -13.313980 	Loss_total: -19.892529
Train Epoch 450 	Loss1: -6.572700 	Loss2: -13.282710 	Loss_total: -19.855410
Train Epoch 500 	Loss1: -6.581871 	Loss2: -13.303087 	Loss_total: -19.884958
Train Epoch 550 	Loss1: -6.573239 	Loss2: -13.252339 	Loss_total: -19.825579
Train Epoch 600 	Loss1: -6.559539 	Loss2: -13.253999 	Loss_total: -19.813538
Tra

In [52]:
# モデル分類のクラスターの結果を確認する
import numpy as np

# ミニバッチサイズ1のテスト用のDataLoaderを用意
dl_bert_test = DataLoader(
    dataset_bert_test, batch_size=1, shuffle=False)


def test(model, device, test_loader):
    model.eval()

    out_targs = []
    ref_targs = []

    # 出力用のリストを用意
    total_num = len(test_loader)
    # index, (target_label, inferenced_label)
    output_list = np.zeros((total_num, 2))

    with torch.no_grad():
        for batch_idx, (target, data) in enumerate(test_loader):
            data = data.to(device)
            target = target.to(device)
            outputs, outputs_overclustering = model(data)

            # 分類結果をリストに追加
            out_targs.append(outputs.argmax(dim=1).cpu())
            ref_targs.append(target[0].cpu())

            # 結果をリストにまとめる
            output_list[batch_idx, 0] = target[0][0].cpu()  # 正解ラベル
            output_list[batch_idx, 1] = outputs.argmax(dim=1).cpu()  # 予測ラベル

    out_targs = torch.cat(out_targs)
    ref_targs = torch.cat(ref_targs)

    return out_targs.view(-1, 1).numpy(), ref_targs.numpy(), output_list

In [53]:
# テストデータで推論を実施
out_targs, ref_targs, output_list = test(model_trained, device, dl_bert_test)

In [54]:
# 混同行列（的な）を作る
matrix = np.zeros((9, 9))

# 縦にlivedoorニュースの正解クラスを、横に判定されたクラスの頻度表を作成
for i in range(len(out_targs)):
    row = ref_targs[i]
    col = out_targs[i]
    matrix[row][col] += 1

np.set_printoptions(suppress=True)
print(matrix)

[[ 59.   0.  28.   6.  12.   6.  12.  40.  17.]
 [ 11.   4.   9.  46.   7.   0.  28.   4.   2.]
 [  2.   1.  26.   2. 108.   1.   8.  17.   1.]
 [ 56.   0.   0.   0.   0.  21.  26.  41.  24.]
 [  1. 106.   6.  38.   0.   1.  14.   0.   2.]
 [  7.   0.   1.   5.   1.  96.  62.   2.   0.]
 [ 24.   2.  38.   7.  39.   2.  14.  17.  31.]
 [  7.   9.  58.  50.   3.   6.  24.  16.   0.]
 [ 28.   0.   0.   2.   0.   5.  14.  44.  68.]]


In [55]:
dic_id2cat

{0: 'kaden-channel',
 1: 'livedoor-homme',
 2: 'smax',
 3: 'sports-watch',
 4: 'dokujo-tsushin',
 5: 'movie-enter',
 6: 'it-life-hack',
 7: 'peachy',
 8: 'topic-news'}

In [56]:
# クラスタの結果を確認
#「sports-watch」の5番目のクラスタの文章、7番目のクラスタの文章
#「topic-news」の5番目のクラスタの文章、7番目のクラスタの文章
# を確認して、クラスタ5とクラスタ7の特徴を見てみます。

import pandas as pd

df2 = pd.DataFrame(output_list)
df2.columns=["正解クラス", "推定クラスタ"]
df2.head()

正解クラス  推定クラスタ
0    5.0     6.0
1    6.0     4.0
2    3.0     8.0
3    5.0     5.0
4    5.0     5.0

In [57]:
df2[(df2['正解クラス']==0) & (df2['推定クラスタ']==5)].head()

正解クラス  推定クラスタ
212     0.0     5.0
592     0.0     5.0
616     0.0     5.0
828     0.0     5.0
1143    0.0     5.0

In [58]:
# dfに元文書を入れている。300文字ほど見る。
print(df.iloc[21, 0][:300])
print(df.iloc[59, 0][:300])

鼻やのどの粘膜の乾燥は、インフルエンザはもちろん副鼻腔炎など、さまざまな不調を引き起こす原因のひとつ。ビジネスパーソンにとってオフィスが乾燥するという場合があると思うが、そんなときに手軽で便利な加湿器が、グリーンハウスから発売されている。USB、シガーソケット、そして同社の別売USB-ACアダプタ「GH-ACC-USBシリーズ」で、出張先のホテルなどのコンセントにも接続できる。超音波の振動を利用して水蒸気を発生させるため、やけどの心配もないし、３時間稼働したら自動的に停止するので、消し忘れの心配をしなくて済む。特に多忙な人をいたわってくれる設計なのだ。しかも、２色展開の本体はもちろん、６色も設
クリスマスや年末年始に向けてイルミネーションが街を彩り、家族や友人たちとワイワイ集まるなど楽しいイベントが増える季節。デジカメの出番も増えるが、暗い場所でキレイに撮れなかったり、動きのあるシーンでブレてしまってはもったいない。カシオの新しい「EXILIM（エクシリム）」なら残したい場面をサクサクきれいに撮れる11月18日発売のEXILIMEX-ZR200は、撮影感覚0.27秒という高速レスポンスで、狙った瞬間を逃さない。つまり、シャッターを押した後、待たずに続けて撮影ができるのだ。「快速シャッター」と名付けられたスピード感のある撮影機能は、ちょっぴりプロの気分になれそうだ。オートフォーカスが0


In [59]:
# dfに元文書を入れている。300文字ほど見る。
print(df.iloc[14, 0][:300])
print(df.iloc[18, 0][:300])

同人誌市場の大きさや、書店へのアクセスに恵まれている日本は、電子書籍にとってまだまだ未開発マーケット。そんななか、電子書籍のメリットを最大限に生かし使いこなしているユーザーも多い。その使い方の実態は…？株式会社ネットエイジアが、ネット上の共通ポイントサービス「ネットマイル」の会員600人および中国人のパネル450人に、電子書籍の利用状況や期待感についてアンケートを実施した。その結果は、日本で電子書籍を「利用している」という人は9.8％、「利用していないが、今後は利用したいと思う」が32.5％、「今後も利用したいと思わない」が57.7％だった。対照的に中国では「利用している」が75.6％と最も多
明日よりセブン＆アイ・ホールディングスは、無料ワイヤレス通信サービス「セブンスポット」をスタートする。セブンスポットでの接続によってオリジナルコンテンツの配布も行うが、第一弾として人気アイドルグループAKBのメンバーがサンタ姿を披露する「AKB４８クリスマス壁紙」の配布が行われる。配布期間はクリスマスが終了する２５日までだ。このサービスは1回につき最大60分間利用することができ、1日につき3回までアクセスが可能だ。利用するためには、「セブンスポット」会員登録が必要でこちらは無料。なお「セブンスポット」が利用可能になるのは以下だ。東京23区内のセブンーイレブン（約770店舗）、イトーヨーカドー（


In [60]:
df2[(df2['正解クラス']==8) & (df2['推定クラスタ']==5)].head(2)

正解クラス  推定クラスタ
215    8.0     5.0
252    8.0     5.0

In [61]:
# dfに元文書を入れている。300文字ほど見る。
print(df.iloc[7, 0][:300])
print(df.iloc[55, 0][:300])

14日、週刊誌「週刊文春」（6月21日号）は、AKB48指原莉乃の元カレを名乗る男性の交際暴露記事を掲載した。もともとAKB48のファンだったという男性が明かす、その内容とは「エッチまで4ヶ月かかった」「別れ話をすると『あたし諦めれん ほんとにここまで好きになったのはじめてなの（中略）エッチだってしたのにふざけんなよ！』と指原からメールが送られてきた」といった衝撃的なもので、ネットニュースを中心とした実に多くのメディアが二次的に取り上げ、ツイッターや掲示板でも大きな話題となった。すると15日、漫画家・小林よしのり氏は、公式ブログ「ゴー宣道場」で「AKB48 指原のスキャンダルについて」というエ
16日、韓国で「金正日萌え」「赤いシャツが好き」などとツイートしたり、北朝鮮当局のアカウント（@uriminzok ）のつぶやきをリツイートした罪で、今年の1月韓国当局に逮捕された青年の公判（通称：「『金正日萌え』ツイート逮捕事件」）が行われた。「金正日萌え」の日本語の「萌え」はそのまま韓国語での発音通りつぶやいたもの。逮捕された青年パク・ジョングン氏（@seouldecadence ）にかかっている疑いは「国家保安法違反」。同法は韓国内で活動している北朝鮮の工作員を処罰するためのもので、韓国当局は「金正日萌え」に関しては日本語の辞書を用いて「萌え」の意味を調べるなどの捜査を行い、パク氏のつぶ


In [62]:
df2[(df2['正解クラス']==8) & (df2['推定クラスタ']==7)].head(2)

正解クラス  推定クラスタ
71     8.0     7.0
116    8.0     7.0

In [63]:
# dfに元文書を入れている。300文字ほど見る。
print(df.iloc[71, 0][:300])
print(df.iloc[76, 0][:300])

12日、韓国の人気お笑い芸人ジョン・ジュンハが韓国のケーブルチャンネル「Y-STAR」のグルメ番組取材のため大阪を訪れ、収録した番組内で「独島（竹島の韓国名）は我が領土だ」と発言したことを複数の韓国メディアが報じた。一連の報道によると、ジョン・ジュンハは日本人歩行者にたこ焼きを勧めながらも、「独島（竹島の韓国名）は我が領土だ」と韓国語で発言し、寿司屋でも食事後に「独島は我が領土」という韓国の歌を自慢気に歌ったとされる。韓国ではこの放送が個人ブログを中心に話題となり、「ジョン・ジュンハさん格好いい!!」「ジョンさんが日本の大阪で愛国心を披露しました。大阪は彼の恋人の故郷でもあります。本当感動しま
8日に大手スーパー「西友」が、中国産のコメを低価格帯の国産米より安い価格で販売すると発表したことを各メディアが報じ、ネット掲示板上で話題になっている。去年の東日本大震災の影響により、国産米の取引価格が上がっている反面、低価格帯の商品も品薄状態にあることから、西友は10日より中国産の米を低価格帯の国産米より約3割安い5キロ1299円で販売するという。同社は国の輸入制度に基づく残留農薬などの検査を行い、安全性にも配慮すると強調しているものの、この報道を受け、ネット掲示板上では「死んでもお断り。中国米食うぐらいならパン食うわ」「安全安心な中国産？なんのジョークだよ」「3割程度の安さなら国産買うわ」「
